### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by mariusvniekerk** [martindurant/filesystem_spec#1]
https://github.com/martindurant/filesystem_spec/blob/825c894d7634ae5546b15be60f5c583bc37edc5d/fsspec/spec.py#L90-L94

We should specify here that this output format has the same structure as `os..walk`

**Comment by martindurant** [comment]
Agreed - `glob` implicitly assumes this. Some of the implementations have this simpler version, though, just a list of paths than some may prefer. Maybe with a different method name?

**Comment by mariusvniekerk** [comment]
I'd probably say that walk should be like os.walk,

`ls(recursive=True)` should be have output like ls
