### ISSUE TITLE
Add implementations?

### ISSUE THREAD

**Issue by martindurant** [martindurant/filesystem_spec#18]
Aside from the sibling projects (s3fs, gcsfs...) that this project is meant to unite, there are many other file-system-like things that would be easy to implement. Those things could live directly within this repo, as local, http and memory do, but would make setting up testing increasingly complicated. 

- (s)ftp
- ssh/scp

Some are already implemented in pyfilsystems2 - can we wrap those or otherwise reuse the code?

**Comment by martindurant** [comment]
(please add your favourites)

**Comment by rabernat** [comment]
zip file?

**Comment by martindurant** [comment]
@rabernat , indeed, good one. I wonder whether its trivial to wrap the pyfilesystems implementations [here](https://docs.pyfilesystem.org/en/latest/builtin.html) which include ZIP and TAR.

**Comment by martindurant** [comment]
Having said that, the builtin python [ZipFile](https://docs.python.org/2/library/zipfile.html#zipfile.ZipFile) and [TarFile](https://docs.python.org/3/library/tarfile.html#tarfile-objects) are straight-forward enough, especially for reading.

**Comment by martindurant** [comment]
The merged PR is read-only. I'll leave a full implementation for later.

Paramiko's [sftp] seems pretty complete for the basis of another implementation.

**Comment by martindurant** [comment]
SFTP added: https://github.com/martindurant/filesystem_spec/pull/20

**Comment by martindurant** [comment]
FTP added, along with AbstractBufferedFile (which can be reused by gcsfs, s3fs, adlfs, azure-blob) https://github.com/martindurant/filesystem_spec/pull/21

**Comment by martindurant** [comment]
webHDFS? 
xref https://github.com/dask/hdfs3/issues/171
