### ISSUE TITLE
Non-plural open_files

### ISSUE THREAD

**Issue by shoyer** [martindurant/filesystem_spec#31]
It would be nice to have an alias that only opened a single file, e.g., `fsspec.open_file` or even `fsspec.open`. Right now idiomatic usage of fsspec for a single file looks pretty awkward with the need for indexing like `[0]`, e.g.,
```python
with fsspec.open_files(path)[0] as f:
    f.write(...)
```

**Comment by martindurant** [comment]
Yes, that certainly sounds reasonable. Would you be worried about tab-completion accidentally getting the wrong one here? It might make sense to call it simply `fsspec.open()`.

**Comment by shoyer** [comment]
I like the look of `fsspec.open()` for a drop-in replacement for `open()`.

I think most tab-completion systems will show both..
