### ISSUE TITLE
Surprising behavior of open_files()

### ISSUE THREAD

**Issue by shoyer** [martindurant/filesystem_spec#32]
h5py now supports file-like objects. This works with the built-in `open()`, but I get an error when I try this with `fsspec`:
```python
import h5py
import fsspec

with fsspec.open_files('test.h5', 'wb')[0] as f:
  with h5py.File(f, 'w') as h5file:
    h5file.attrs['foo'] = 'bar'
```
```
---------------------------------------------------------------------------
NotADirectoryError                        Traceback (most recent call last)
<ipython-input-15-bc0b4a6a665e> in <module>()
      2 import fsspec
      3 
----> 4 with fsspec.open_files('test.h5', 'wb')[0] as f:
      5   with h5py.File(f, 'w') as h5file:
      6     h5file.attrs['foo'] = 'bar'

/usr/local/lib/python3.6/dist-packages/fsspec/core.py in __enter__(self)
     57         mode = self.mode.replace('t', '').replace('b', '') + 'b'
     58 
---> 59         f = self.fs.open(self.path, mode=mode)
     60 
     61         fobjects = [f]

/usr/local/lib/python3.6/dist-packages/fsspec/spec.py in open(self, path, mode, block_size, **kwargs)
    562             ac = kwargs.pop('autocommit', not self._intrans)
    563             f = self._open(path, mode=mode, block_size=block_size,
--> 564                            autocommit=ac, **kwargs)
    565             if not ac:
    566                 self.transaction.files.append(f)

/usr/local/lib/python3.6/dist-packages/fsspec/implementations/local.py in _open(self, path, mode, block_size, **kwargs)
     70 
     71     def _open(self, path, mode='rb', block_size=None, **kwargs):
---> 72         return LocalFileOpener(path, mode, **kwargs)
     73 
     74     def touch(self, path, **kwargs):

/usr/local/lib/python3.6/dist-packages/fsspec/implementations/local.py in __init__(self, path, mode, autocommit)
     85         self.autocommit = autocommit
     86         if autocommit or 'w' not in mode:
---> 87             self.f = open(path, mode=mode)
     88         else:
     89             # TODO: check if path is writable?

NotADirectoryError: [Errno 20] Not a directory: 'test.h5/0.part'
```

Working example with `open()`:
```python
with open('test.h5', 'wb') as f:
  with h5py.File(f, 'w') as h5file:
    h5file.attrs['foo'] = 'bar'
```

**Comment by shoyer** [comment]
I get a similar error when I try writing a file with `scipy.io.netcdf_file`:
```python
import scipy.io
import fsspec

with fsspec.open_files('test2.nc', 'wb')[0] as f:
  with scipy.io.netcdf_file(f, 'w') as nc:
    nc.foo = 'bar'
```
```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-27-a83f6b4f3eff> in <module>()
      2 import fsspec
      3 
----> 4 with fsspec.open_files('test2.nc', 'wb')[0] as f:
      5   with scipy.io.netcdf_file(f, 'w') as nc:
      6     nc.foo = 'bar'

/usr/local/lib/python3.6/dist-packages/fsspec/core.py in __enter__(self)
     57         mode = self.mode.replace('t', '').replace('b', '') + 'b'
     58 
---> 59         f = self.fs.open(self.path, mode=mode)
     60 
     61         fobjects = [f]

/usr/local/lib/python3.6/dist-packages/fsspec/spec.py in open(self, path, mode, block_size, **kwargs)
    562             ac = kwargs.pop('autocommit', not self._intrans)
    563             f = self._open(path, mode=mode, block_size=block_size,
--> 564                            autocommit=ac, **kwargs)
    565             if not ac:
    566                 self.transaction.files.append(f)

/usr/local/lib/python3.6/dist-packages/fsspec/implementations/local.py in _open(self, path, mode, block_size, **kwargs)
     70 
     71     def _open(self, path, mode='rb', block_size=None, **kwargs):
---> 72         return LocalFileOpener(path, mode, **kwargs)
     73 
     74     def touch(self, path, **kwargs):

/usr/local/lib/python3.6/dist-packages/fsspec/implementations/local.py in __init__(self, path, mode, autocommit)
     85         self.autocommit = autocommit
     86         if autocommit or 'w' not in mode:
---> 87             self.f = open(path, mode=mode)
     88         else:
     89             # TODO: check if path is writable?

FileNotFoundError: [Errno 2] No such file or directory: 'test2.nc/0.part'
```

**Comment by martindurant** [comment]
I would say this is the same issue as #31 - open_files for writing will get you multiple open files with different names, even if you intend to write to only one. Again, the single-file case should be special. The following works:
```
In [14]: import scipy.io
    ...: import fsspec
    ...:
    ...: with fsspec.open_files(['test2.nc'], 'wb')[0] as f:
    ...:   with scipy.io.netcdf_file(f, 'w') as nc:
    ...:     nc.foo = 'bar'
    ...:
```

**Comment by martindurant** [comment]
(note the input is a list here)

**Comment by shoyer** [comment]
I guess I'm a little puzzled. Why does `fsspec.open_files('test2.nc', 'wb')` do something different from `fsspec.open_files(['test2.nc'], 'wb')`? This isn't something I would guess from the docstring.

**Comment by martindurant** [comment]
The h5py case just uses fspath to get the "real local path" of an open file-like object, it doesn't actually use the file-like object's methods. fsspec *could* implement the fspath protocol, but it makes no sense for any file except the local one.

**Comment by martindurant** [comment]
Docstring updates welcome.

`fsspec.open_files('test.*.nc', 'wb', num=..)` -> open some files for writing, filling out the * with numbers; this is what is getting triggered in your case. In the case of no *, the path is assumed to be a directory, and to put files within it. 

`fsspec.open_files(['test2.nc'], 'wb')` skips the search and substitution steps and assumes that the paths given are the final ones to use.

**Comment by martindurant** [comment]
The following small change would allow for the "write to a specific file" to work - i.e., if num==1
```diff
--- a/fsspec/core.py
+++ b/fsspec/core.py
@@ -247,7 +247,7 @@ def _expand_paths(path, name_function, num):
     if isinstance(path, str):
         if path.count('*') > 1:
             raise ValueError("Output path spec must contain at most one '*'.")
-        elif '*' not in path:
+        elif '*' not in path and num > 1:
             path = os.path.join(path, '*.part')

         if name_function is None:
```

**Comment by shoyer** [comment]
> In the case of no *, the path is assumed to be a directory, and to put files within it.

This feels a little magical for my taste. I would expect to need to write something like `fsspec.open_files('test/*.part', 'wb')` to get this.

The separate `fsspec.open()` would help by adding a more obvious alternative.

Tweaking this heuristic to add even more special case logic seems dangerous. A few other options I like:
- Raises an error if `*` isn't found instead of implicitly adding `*.part` to the end.
- Changing the default value `num=None`, and require explicitly passing `num` if you want automatic expansion. `fsopen.open_files('mytest', 'wb', num=1`) is not so surprising.

**Comment by martindurant** [comment]
You may well be right. This was, of course, copied from Dask, where things are made of multiple parts by default.

**Comment by shoyer** [comment]
On a related note, at Google we use the naming convention of appending `-SSSSS-of-NNNNN` for indicating automatically sharded files, e.g., `myfile-00000-of-00100`, `myfile-00001-of-00100`, `myfile-00002-of-00100`, etc.

Apache Beam uses this convention too by default. See `shard_name_template`:
https://beam.apache.org/releases/pydoc/2.10.0/apache_beam.io.textio.html

Anyways, just something to consider. (And note that Apache Beam is yet another library, with use-cases similar to dask, that defines its own Python file system abstraction.)

**Comment by martindurant** [comment]
You can pass your own `name_function=`, but changing the default would be easy enough.
