### ISSUE TITLE
Support encoding for LocalFileOpener 

### ISSUE THREAD

**Issue by gsakkis** [martindurant/filesystem_spec#35]
Currently local file `open()` supports only `mode`. It would be useful to add at least `encoding` (since it's implemented e.g. for `S3FileSystem`) if not all builtin `open` parameters (`buffering`, `errors`, etc).

**Comment by martindurant** [comment]
If you use `fsspec.open`, you can pass encoding there. 
In the long run, it may be nice to expose the whole spec interface, where URL protocols are used to delegate to individual implementations...

**Comment by gsakkis** [comment]
Thanks, `fsspec.OpenFile` works for me (`open` is not on 0.2.0).

**Comment by martindurant** [comment]
Ah, sorry. Maybe I should micro-release sometime. `open_files(...)[0]` does essentially the same thing as `open(...)`, which may be more convenient that calling `OpenFile` directly.
