### ISSUE TITLE
Committer

### ISSUE THREAD

**Issue by martindurant** [martindurant/filesystem_spec#4]
Would like some general method by which files can be written to a temporary location, probably on the same file-system, and then all committed together later, when all writing has completed; or aborting the whole process and leaving the target location unchanged. This makes the writing process (almost) atomic.

Would ideally be not just for single files, but for groups such as "all files below `path/`" or "all writes until a commit is requested". Of course, the default would still be to auto-commit, to write to the real final location as soon as possible.

In a FS like HDFS, this would be by `mv`-ing the files from the temporary location. In a FS like S3, uploads of files larger than the smallest block size uses a blocked upload, which needs finalising anyway, and can be aborted (whereas there is no move, only copy-and-delete). Exactly *how* an implementation achieves temporary writes is not to be defined here.

Importantly, the concept should be portable across instances of the file-system in different processes, so that a batch of files can be written in parallel, e.g., with Dask, and committed together. Perhaps each instance notes only the files that it writes, but then all must still be around at commit time. I do not have a good idea of how that might be achieved, suggestions welcome.

**Comment by martindurant** [comment]
@mariusvniekerk , can you please link the issue where you first mentioned this idea?

**Comment by mariusvniekerk** [comment]
See https://github.com/dask/dask/issues/2923 for a discussion on s3

**Comment by mariusvniekerk** [comment]
cc @jakirkham
