### ISSUE TITLE
Best way to determine file or url exists?

### ISSUE THREAD

**Issue by youngsaj** [martindurant/filesystem_spec#42]
with of as f:
      f.exists(path)

That's fine for local files.  However, I ultimately want to use this in underlying code that intake will use, and path being https, s3 or c:\ can all be valid possibilities.
HTTPfile doesn't have an exists(), what is the recommended way to do this?

**Comment by martindurant** [comment]
File types that derive from AbstractBufferedFile normally have an `fs` attribute to act on, you probably meant `f.fs.exists(path)` - although you normally have the filesystem instance hanging around too. I can add this to HTTPFile, but the HTTPFileSystem is not very capable...

In general, file-systems do provide an `exists()` method as you describe. However, for HTTP, you cannot "list" a directory or get info on some url, so there's no way to know if a given URL exists except to try to read from it. This is a fundamental limitation of the protocol, and there is nothing we can do about it. There do exist some layers on top of HTTP specifically for filesystem-like operation, but that would depend on a server-side implementation, which is very rare.

**Comment by martindurant** [comment]
Maybe `exists` could be implemented by trying GET on the URL with streaming and then immediately closing the connection?

**Comment by youngsaj** [comment]
Seems like a good idea, but not well versed at GET myself., I tend to find high level libraries such as this.

**Comment by youngsaj** [comment]
a simple test 
urlnosuch = 'https://six-library.s3.amazonaws.com/sicd_example_nofile.nitf'
import requests
r = requests.get(urlnosuch)
r.ok

False

urlsmall = 'https://six-library.s3.amazonaws.com/sicd_example_RMA_RGZERO_RE32F_IM32F_cropped_multiple_image_segments.nitf'
r = requests.get(urlsmall)
r.ok

True

**Comment by martindurant** [comment]
And would you think that `urlnosuch = 'http://not.a.server/test_file'` should simply result in `False`, or should the resultant `ConnectionError` come through to the user?

**Comment by youngsaj** [comment]
I'm coming from a user of API, I would want it to be as close to how a file system would work.  What I see looking good at a glance.

**Comment by martindurant** [comment]
Done.
