### ISSUE TITLE
HTTPfile object has no attribute kwargs

### ISSUE THREAD

**Issue by youngsaj** [martindurant/filesystem_spec#44]
urlsmall = 'https://six-library.s3.amazonaws.com/sicd_example_RMA_RGZERO_RE32F_IM32F_cropped_multiple_image_segments.nitf'
#test = cf_sicd.Reader(urlsmall)
test = fsspec.open(urlsmall)

test.fs.exists(test.path)

True

with test as fid:
    fid.read(9)

AttributeError                            Traceback (most recent call last)
<ipython-input-9-869a2fab67bb> in <module>
----> 1 with test as fid:
      2     fid.read(9)

C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\fsspec-0.2.0+28.g9b388d4-py3.7.egg\fsspec\core.py in __enter__(self)
     57         mode = self.mode.replace('t', '').replace('b', '') + 'b'
     58 
---> 59         f = self.fs.open(self.path, mode=mode)
     60 
     61         fobjects = [f]

C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\fsspec-0.2.0+28.g9b388d4-py3.7.egg\fsspec\spec.py in open(self, path, mode, block_size, **kwargs)
    584             ac = kwargs.pop('autocommit', not self._intrans)
    585             f = self._open(path, mode=mode, block_size=block_size,
--> 586                            autocommit=ac, **kwargs)
    587             if not ac:
    588                 self.transaction.files.append(f)

C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\fsspec-0.2.0+28.g9b388d4-py3.7.egg\fsspec\implementations\http.py in _open(self, url, mode, block_size, **kwargs)
    128         kw.pop('autocommit', None)
    129         if block_size:
--> 130             return HTTPFile(self, url, self.session, block_size, **kw)
    131         else:
    132             kw['stream'] = True

C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\fsspec-0.2.0+28.g9b388d4-py3.7.egg\fsspec\implementations\http.py in __init__(self, fs, url, session, block_size, mode, **kwargs)
    175         try:
    176             size = file_size(url, self.session, allow_redirects=True,
--> 177                              **self.kwargs)
    178         except (ValueError, requests.HTTPError):
    179             # No size information - only allow read() and no seek()

AttributeError: 'HTTPFile' object has no attribute 'kwargs'

**Comment by martindurant** [comment]
OK, clearly I was hasty; should really have some tests for this FS...

**Comment by martindurant** [comment]
Please try again from master now, following 7c64ceb23bd1c206b4ddde208b3827ac18bf2523

**Comment by youngsaj** [comment]
Working as expected!  https and local files working fine.
