### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by rabernat** [martindurant/filesystem_spec#49]
There has been a bit of development since the 0.2.0 release. I'm wondering when the next release is planned. I am about to release a version of xmitgcm that needs the feature added in #46, so I need to decide what to do about the dependency. I would love to just be able to depend on 0.2.1, rather than github master. But I don't want to rush a release unnecessarily.

**Comment by martindurant** [comment]
I *had* wanted to wait until I had done the compat for gcsfs, and then make a bigger release, but there is nothing preventing a 0.2.1 right now - or when I get around to it.

**Comment by martindurant** [comment]
https://pypi.org/project/fsspec/#history 0.2.1 on pypi, coming to conda soon.

**Comment by rabernat** [comment]
amazing thank you @martindurant!

**Comment by martindurant** [comment]
Done https://github.com/conda-forge/filesystem-spec-feedstock/pull/6
