### ISSUE TITLE
What to do about FSs that don’t glob?

### ISSUE THREAD

**Issue by mmccarty** [martindurant/filesystem_spec#9]
Many file system libraries support glob strings (``s3fs``, ``gcsfs``, and  some of the libraries in [dask.bytes](https://github.com/dask/dask/blob/master/dask/bytes)), however some like [HTTPFileSystem](https://github.com/dask/dask/blob/master/dask/bytes/http.py#L32) do not. In this case, it is difficult (if not impossible) since HTTP servers don't always list directories.

- What are other examples?
- Would is be possible to come up with a standard? 
- Or perhaps a fall back plan? For example, with the case of HTTPFileSystem, try to list with a GET request to the parent path to list and then match on the glob string.  If the GET request fails, fall back to S3FS, GCSFS, or FTPFS.

**Comment by jbednar** [comment]
I think it would be useful to come up with some examples of useful dataset collections stored on HTTPS, and then see what it would take to support those.  E.g. I can't tell right off how https://landsat.usgs.gov/landsat-data-access is stored, but that's a suitable set of data worth accessing...

**Comment by martindurant** [comment]
@jbednar , I suspect that specific HTTP endpoints (REST) will get their own plugins calling the endpoints directly, or wrap a package that formats queries. In this case, it looks like `https://github.com/USGS-EROS/espa-api/blob/master/examples/api_demo.ipynb` shows how to do this - and it's not the case that the data can be described as any set of "files" or discrete URLs.

**Comment by jbednar** [comment]
I think REST endpoints are a separate issue; I'm mainly concerned with HTTP being used as if it were FTP, i.e., to serve a bunch of files in directories.

**Comment by martindurant** [comment]
You mean something like python's `http.server`, where a list of files is presented as a load of HREFs? That's certainly doable, with a few assumptions. I wonder if it would be good to leverage beautiful soup to get a set of links of some remote page. Then, if a URL is "http://myserver/path/to/*.csv", would do a GET to "http://myserver/path/to/" and see how many matching URLs are found in the page, if it's reachable at all.
